### ISSUE TITLE
Is it right choice?

### ISSUE THREAD

**Issue by masihfathi** [tmarois/Filebase#13]
Hi,
We have a email marketing application, table of delivery email for tracking email got more than 1 billion and sql got lag. right know is it right choice to use filebase?  will we have limitation in  speed of reading and writing?

**Comment by timothymarois** [comment]
Hey.

Sorry for the delay. For the size youre thinking about I wouldnt suggest using flat file. It depends though if you’re using it for high colume traffic or archival storage. We use it on website content (almost like caching system) and we use it to cache our advertising systems. Flat files are good because its cheaper ans uses minimal resources. I’d suggest lokking into Amazon Web Services as they offer a large range of platforms.
