### ISSUE TITLE
Use with Eloquent

### ISSUE THREAD

**Issue by chriship** [tmarois/Filebase#66]
Is it possible to use this with Eloquent so I can call things like MyClass::all()?

**Comment by timothymarois** [comment]
HI @chriship 

It is possible to build a wrapper class/object that can render your query results, then pop it into filebase db and vice-versa. I could see where filebase could be used as a cache instead of going directly into the db if data exists in filebase. I dont think there are any third-party packages that have publicly shared this feature yet, but it is possible, and for the call of `all()` you can throw all the items from filebase into a `collection` object with Laravel, and that would give you all the functionality you require.

**Comment by chriship** [comment]
Great, thanks.
