### ISSUE TITLE
findAll() not working as expected

### ISSUE THREAD

**Issue by MarcelHekkert** [tmarois/Filebase#7]
The function findAll isn't working as expected. When it does it leaks the config with each document.

`
    $users = new \Filebase\Database([
        'dir' => '/storage/users',
    ]);

// displays number of users in the database
echo $users->count();  // works!

// Find All Users and display their email addresses

$users->findAll();  // No result!
foreach($users as $user)
{
    echo $user->email;
}

$u = $users->findAll();  // Result, but with a config on each result!
foreach($u as $user)
{
    echo $user->email;
}
`

**Comment by timothymarois** [comment]
You might need to be more specific in your example, you have `findAll()` both of those should receive the same result, and as for the data itself, there are boolean arguments you can pass in `findAll` method. which allows you to return "only" the data of the documents themselves. 

Using `true` would allow it to only give you the document data.  currently, with each result, it gives the document configs so that you can run arrays and do batch updates. with `update()`, `save()`, `delete()` etc without having to locate the document again. But if you only wish to return the data you can use the arguments below.

`$db->findAll(true,true)`

**Comment by timothymarois** [comment]
@MarcelHekkert Assuming you have nothing more to say about this issue, without further evidence I hereby declare this issue void.

**Comment by timothymarois** [comment]
@MarcelHekkert Was just thinking that you don't need to use `findAll` if you don't want the config variables leaked. To save memory you can run the query itself such as `$db->query()->results()` which will give you all the items in the database and returns only their data (not the configuration variables), that is most likely what you are looking for. I have made a couple updates as of yesterday, you can see them in the changelog. Such as the `select()` method etc. Let me know how you make out.
