### ISSUE TITLE
Feature request: REST API

### ISSUE THREAD

**Issue by BasToTheMax** [tmarois/Filebase#72]
When you create a JavaScript site, you want to connect to the database. It should be easy to add a build in rest api, instead of creating at yourself.

**Comment by timothymarois** [comment]
Hey, @BasToTheMax Filebase is only the database driver/storage for your data. If you want a REST API to work with the data/extract etc, you should look into building a PHP API using a framework like Laravel, which makes things incredibly easy. Not too sure on the javascript side unless you use NodeJS and that is probably equivalent, however, since this is a PHP package, I'd recommend staying within that otherwise it would be a lot more work for you. 

Going to close this for now since it's not exactly related to the package.
